"""
Interview plan built at resume upload / session start.

Skill questions are generated by Qwen at upload (cached). Bank/fallback text
is only a safety net if the model is down. Live turns phrase those seeds and
write project follow-ups — they do not invent a new skill syllabus.
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any, Dict, List, Optional, Sequence

from interviewer.services.interview_structure import (
    DURATION_SECONDS,
    MAX_PROJECTS,
    MAX_SKILLS,
    QUESTIONS_PER_PROJECT,
    QUESTIONS_PER_SKILL,
    WRAP_UP_SECONDS,
    planned_question_count,
)
from interviewer.services.resume import TECH_VOCAB


OPENER_BY_TRACK = {
    "aiml": "aiml-project-ownership-01",
    "webd": "webd-project-ownership-01",
    "frontend": "webd-project-ownership-01",
    "backend": "aiml-project-ownership-01",
    "hr": "hr-intro-01",
    "resume": "aiml-project-ownership-01",
    "general_cs": "aiml-project-ownership-01",
    "software_engineering": "aiml-project-ownership-01",
}

SKIP_COMPETENCIES = frozenset({
    "project_ownership",
    "communication",
    "technical_communication",
    "hiring",
    "conflict_resolution",
})

FOUNDATION_SLOTS = (
    {
        "skill": "Object-Oriented Programming",
        "kind": "foundation",
        "aliases": ("oop", "oops", "object-oriented programming", "object oriented programming"),
        "preferred_ids": ("cs-oop-polymorphism-01", "cs-oop-composition-02", "cs-oop-solid-03"),
        "queries": (
            "object oriented polymorphism encapsulation inheritance",
            "composition vs inheritance solid",
            "liskov open closed principle",
        ),
        "fallbacks": (
            "Can you explain the difference between compile-time and runtime polymorphism with a concrete example?",
            "Why is composition over inheritance widely recommended, and when is inheritance a poor choice?",
            "How does the Liskov Substitution Principle stop a subclass from breaking callers of the base type?",
        ),
    },
    {
        "skill": "Data Structures and Algorithms",
        "kind": "foundation",
        "aliases": ("dsa", "data structures", "data structures and algorithms", "algorithms"),
        "preferred_ids": ("cs-dsa-hash-table-01", "cs-dsa-lru-cache-02", "cs-dsa-two-pointers-03"),
        "queries": (
            "hash table collision load factor",
            "lru cache hashmap doubly linked list",
            "linked list cycle two pointers",
        ),
        "fallbacks": (
            "Why is hash table lookup O(1) on average, and what makes it degrade to O(N)?",
            "How would you design an LRU cache so get and put are both O(1)?",
            "How would you detect a cycle in a linked list in linear time and constant extra memory?",
        ),
    },
)

_CV_TERM_RE = re.compile(
    r"\b(?:MobileNetV2|MobileNet|ResNet50|ResNet|EfficientNet|YOLO|ISIC|"
    r"class[- ]weights?|data augmentation|transfer learning|confusion matrix|"
    r"sensitivity|specificity|precision[- ]recall|false negatives?|"
    r"Keras|TensorFlow|PyTorch|NumPy|Pandas|OpenCV|scikit[- ]learn|"
    r"GIL|asyncio|multiprocessing|generator|decorator|type hints?|"
    r"gRPC|mTLS|LangGraph|vLLM|DuckDB|FastAPI|Docker|Kubernetes|"
    r"hash table|linked list|binary search|heap|LRU|"
    r"polymorphism|inheritance|composition|encapsulation)\b",
    re.IGNORECASE,
)

_SKILL_QUERY_HINTS = {
    "python": ("python GIL multiprocessing", "python generators yield", "numpy pandas pipeline"),
    "tensorflow": ("transfer learning CNN freeze layers", "keras class imbalance", "model evaluation threshold"),
    "keras": ("keras transfer learning", "class weights augmentation", "confusion matrix sensitivity"),
    "pytorch": ("pytorch dataloader autograd", "cnn transfer learning", "training loop overfitting"),
    "java": ("java hashmap equals hashcode", "java memory garbage collection", "java concurrency synchronized"),
    "sql": ("sql indexes b-tree", "sql acid isolation", "query plan"),
    "javascript": ("javascript event loop", "closures this", "promises async"),
    "react": ("react state rendering", "hooks reconciliation", "controlled components"),
    "docker": ("docker layers image", "container networking", "multi-stage build"),
}

_SKILL_COMPETENCIES = {
    "python": {"python"},
    "tensorflow": {"deep_learning", "model_training", "model_evaluation", "ml_deployment", "data_validation"},
    "keras": {"deep_learning", "model_training", "model_evaluation", "data_validation"},
    "pytorch": {"deep_learning", "model_training", "model_evaluation", "ml_deployment"},
    "java": {"java"},
    "sql": {"database_systems"},
    "javascript": {"frontend_state"},
    "react": {"frontend_state"},
    "docker": {"ml_deployment", "reliability"},
}

_SKILL_TERM_ALLOW = {
    "python": ("gil", "asyncio", "multiprocessing", "generator", "numpy", "pandas", "decorator", "typing"),
    "tensorflow": ("keras", "mobilenet", "resnet", "efficientnet", "transfer learning", "class weight", "augmentation", "cnn"),
    "keras": ("mobilenet", "resnet", "transfer learning", "class weight", "augmentation", "callback"),
    "pytorch": ("dataloader", "autograd", "cuda", "mobilenet", "resnet", "transfer learning"),
    "java": ("hashmap", "garbage", "thread", "synchronized", "jvm"),
    "sql": ("index", "acid", "isolation", "join", "query"),
}


def _record_id(record: Optional[Dict[str, Any]]) -> Optional[str]:
    if not record:
        return None
    return record.get("id")


def _record_text(record: Optional[Dict[str, Any]]) -> str:
    if not record:
        return ""
    return str(record.get("question") or "").strip()


def _usable_skill_record(record: Optional[Dict[str, Any]], skill: str = "", kind: str = "") -> bool:
    if not record or not _record_text(record):
        return False
    competency = str(record.get("competency") or "").strip().lower()
    topic = str(record.get("topic") or "").strip().lower()
    question = _record_text(record).lower()
    if competency in SKIP_COMPETENCIES:
        return False
    if "project" in topic or competency == "project_ownership":
        return False
    skill_l = str(skill or "").strip().lower()
    if kind == "foundation":
        if "object" in skill_l:
            return "object" in competency or "oop" in competency
        if "data" in skill_l or "algorithm" in skill_l or skill_l == "dsa":
            return "data_structure" in competency or "algorithm" in competency
        return True
    if not skill_l:
        return True
    allowed = _SKILL_COMPETENCIES.get(skill_l)
    if allowed:
        return competency in allowed or skill_l in competency or skill_l in question
    tokens = {t for t in re.findall(r"[a-z0-9]+", skill_l) if len(t) > 2}
    blob = f"{competency} {topic} {question}"
    return any(token in blob for token in tokens)


def _norm_question(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", (text or "").lower()).strip()


def _stable_pick(items: Sequence[Any], seed: str) -> List[Any]:
    """Deterministic order per CV so the same resume is stable, different CVs differ."""
    if not items:
        return []
    digest = hashlib.sha256((seed or "cv").encode("utf-8", errors="replace")).digest()

    def key(item: Any) -> bytes:
        raw = item if isinstance(item, str) else str(item)
        return hashlib.sha256(digest + raw.encode("utf-8", errors="replace")).digest()

    return sorted(items, key=key)


def _cv_terms(resume_text: str, skill: str) -> List[str]:
    blob = resume_text or ""
    found: list[str] = []
    seen: set[str] = set()

    def add(term: str) -> None:
        clean = re.sub(r"\s+", " ", str(term or "")).strip()
        key = clean.lower()
        if not clean or key in seen or key == str(skill).lower():
            return
        seen.add(key)
        found.append(clean)

    skill_l = str(skill or "").lower()
    for match in _CV_TERM_RE.findall(blob):
        add(match)
    for tech in TECH_VOCAB:
        if tech.lower() == skill_l:
            continue
        if re.search(rf"\b{re.escape(tech)}\b", blob, flags=re.IGNORECASE):
            add(tech)
    allow = _SKILL_TERM_ALLOW.get(skill_l)
    if allow:
        found = [term for term in found if any(key in term.lower() for key in allow)]
    elif "object" in skill_l:
        found = [term for term in found if any(k in term.lower() for k in ("polymorphism", "inheritance", "composition", "encapsulation"))]
    elif "data structure" in skill_l or skill_l in {"dsa", "algorithms"}:
        found = [term for term in found if any(k in term.lower() for k in ("hash", "linked list", "lru", "heap", "binary search"))]
    return found[:10]


def _skill_queries(skill: str, terms: Sequence[str]) -> List[str]:
    queries = [str(skill)]
    key = str(skill or "").strip().lower()
    queries.extend(_SKILL_QUERY_HINTS.get(key, ()))
    if terms:
        queries.append(f"{skill} " + " ".join(list(terms)[:3]))
    # de-dupe, keep order
    out, seen = [], set()
    for q in queries:
        n = q.strip().lower()
        if n and n not in seen:
            seen.add(n)
            out.append(q.strip())
    return out


def _grounded_fallbacks(skill: str, kind: str, terms: Sequence[str]) -> List[str]:
    skill = str(skill or "this skill").strip()
    a = terms[0] if terms else ""
    b = terms[1] if len(terms) > 1 else ""
    out: list[str] = []
    if kind != "foundation":
        if a and b:
            out.append(
                f"In {skill}, when do you choose {a} over {b}, and what is the failure mode of the wrong pick?"
            )
        if a:
            out.append(
                f"How does {skill} use {a} under the hood, and what breaks if that assumption is wrong?"
            )
            out.append(
                f"How would you debug a silent failure in a {skill} pipeline that involves {a}?"
            )
        out.append(
            f"What {skill} API or data structure did you rely on for correctness, and why not a simpler alternative?"
        )
        out.append(
            f"How do you test a {skill} change so a regression in types, shapes, or latency is caught before production?"
        )
    return out


def _pick_bank_questions(
    question_bank_rag: Any,
    *,
    skill: str,
    kind: str,
    preferred_ids: tuple[str, ...] = (),
    queries: Sequence[str] = (),
    used_ids: set[str],
    used_questions: List[str],
    track: str,
    limit: int,
) -> List[Dict[str, Any]]:
    found: list[Dict[str, Any]] = []
    if not question_bank_rag or limit <= 0:
        return found

    def take(record: Optional[Dict[str, Any]]) -> bool:
        if not _usable_skill_record(record, skill, kind):
            return False
        qid = _record_id(record)
        text = _record_text(record)
        if not text:
            return False
        if qid and qid in used_ids:
            return False
        if _norm_question(text) in {_norm_question(q) for q in used_questions}:
            return False
        found.append(record)
        if qid:
            used_ids.add(qid)
        used_questions.append(text)
        return True

    for qid in preferred_ids:
        if len(found) >= limit:
            break
        if qid in used_ids or not hasattr(question_bank_rag, "get_record"):
            continue
        take(question_bank_rag.get_record(qid))

    if found and hasattr(question_bank_rag, "get_record"):
        try:
            from interviewer.services.question_bank import get_question_bank
            bank = get_question_bank()
            first = bank.get(_record_id(found[0]))
            if first is not None:
                for follow in bank.follow_ups(first, exclude_ids=used_ids):
                    if len(found) >= limit:
                        break
                    take(follow.as_dict())
        except Exception:
            pass

    if hasattr(question_bank_rag, "retrieve_scored_records"):
        bank_filter = None if str(track).lower() in ("resume", "none", "") else track
        for query in queries:
            if len(found) >= limit:
                break
            hits = question_bank_rag.retrieve_scored_records(
                query=query,
                top_k=6,
                exclude_questions=used_questions,
                track=bank_filter,
                target_difficulty=2,
            ) or []
            for hit in hits:
                if len(found) >= limit:
                    break
                take(hit)
    return found


def _slot_questions(
    *,
    skill: str,
    kind: str,
    preferred_ids: tuple[str, ...] = (),
    queries: Sequence[str] = (),
    fallbacks: Sequence[str] = (),
    resume_text: str,
    seed: str,
    used_ids: set[str],
    used_questions: List[str],
    question_bank_rag: Any,
    track: str,
    count: int,
) -> Dict[str, Any]:
    terms = _cv_terms(resume_text, skill)
    query_list = list(queries) + _skill_queries(skill, terms)
    records = _pick_bank_questions(
        question_bank_rag,
        skill=skill,
        kind=kind,
        preferred_ids=preferred_ids,
        queries=query_list,
        used_ids=used_ids,
        used_questions=used_questions,
        track=track,
        limit=count,
    )
    texts = [_record_text(r) for r in records if _record_text(r)]
    ids = [_record_id(r) for r in records if _record_id(r)]

    extras = [t for t in list(fallbacks) + _grounded_fallbacks(skill, kind, terms) if t]
    extras = _stable_pick(extras, f"{seed}|{skill}|{kind}")
    have = {_norm_question(t) for t in texts}
    for extra in extras:
        if len(texts) >= count:
            break
        key = _norm_question(extra)
        if not key or key in have:
            continue
        have.add(key)
        texts.append(extra)
        used_questions.append(extra)

    texts = texts[:count]
    if not texts:
        texts = [f"Explain a concrete {skill} failure you have seen, including the data structure or API involved."]
    return {
        "skill": skill,
        "kind": kind,
        "question_ids": ids,
        "base_question": texts[0],
        "questions": texts,
        "cv_terms": terms[:6],
    }


def build_interview_plan(
    candidate_dict: Dict[str, Any],
    question_bank_rag: Any = None,
    max_projects: int = MAX_PROJECTS,
    max_skills: int = MAX_SKILLS,
) -> Dict[str, Any]:
    """Pick opener, OOPs/DSA, and 3 locked questions per skill before the first spoken turn."""
    projects = list(candidate_dict.get("projects") or [])[:max_projects]
    cv_skills = list(candidate_dict.get("skills") or [])[:max_skills]
    track = (
        candidate_dict.get("bank_track")
        or candidate_dict.get("target_track")
        or "resume"
    )
    if not track or str(track).lower() in ("none", "null"):
        track = "resume"
    style = str(candidate_dict.get("interview_style") or "").lower()
    opener_id = OPENER_BY_TRACK.get(str(track).lower(), OPENER_BY_TRACK["resume"])
    resume_text = str(
        candidate_dict.get("resume_text")
        or candidate_dict.get("raw_text")
        or candidate_dict.get("resume_context")
        or ""
    )
    seed = "|".join(
        [
            str(candidate_dict.get("name") or ""),
            ",".join(projects),
            ",".join(cv_skills),
            resume_text[:400],
        ]
    )

    skill_slots: List[Dict[str, Any]] = []
    used_ids = {opener_id} if opener_id else set()
    used_questions: List[str] = []
    per_skill = max(3, int(QUESTIONS_PER_SKILL or 3))

    if question_bank_rag and hasattr(question_bank_rag, "get_record") and opener_id:
        opener = question_bank_rag.get_record(opener_id)
        if opener and opener.get("question"):
            used_questions.append(opener["question"])

    foundation_names = set()
    if style != "behavioral" and str(track).lower() != "hr":
        for foundation in FOUNDATION_SLOTS:
            foundation_names.add(foundation["skill"].strip().lower())
            foundation_names.update(foundation["aliases"])
            skill_slots.append(
                _slot_questions(
                    skill=foundation["skill"],
                    kind="foundation",
                    preferred_ids=foundation["preferred_ids"],
                    queries=foundation["queries"],
                    fallbacks=foundation["fallbacks"],
                    resume_text=resume_text,
                    seed=seed,
                    used_ids=used_ids,
                    used_questions=used_questions,
                    question_bank_rag=question_bank_rag,
                    track=track,
                    count=per_skill,
                )
            )

    for skill in cv_skills:
        skill_l = str(skill).strip().lower()
        if not skill_l or skill_l in foundation_names:
            continue
        skill_slots.append(
            _slot_questions(
                skill=skill,
                kind="cv",
                queries=_skill_queries(skill, _cv_terms(resume_text, skill)),
                resume_text=resume_text,
                seed=seed,
                used_ids=used_ids,
                used_questions=used_questions,
                question_bank_rag=question_bank_rag,
                track=track,
                count=per_skill,
            )
        )

    skill_names = [slot["skill"] for slot in skill_slots]
    return {
        "track": track,
        "opener_id": opener_id,
        "project_names": projects,
        "skill_names": skill_names,
        "skill_slots": skill_slots,
        "skill_questions_source": "fallback",
        "structure": "warmup -> projects -> oops/dsa -> cv skills -> closing",
        "duration_seconds": DURATION_SECONDS,
        "wrap_up_seconds": WRAP_UP_SECONDS,
        "questions_per_project": QUESTIONS_PER_PROJECT,
        "questions_per_skill": per_skill,
        "total_questions": planned_question_count(len(projects), len(skill_names)),
    }


def _clean_generated_question(text: Any) -> str:
    question = re.sub(r"\s+", " ", str(text or "")).strip().strip("\"'`")
    question = re.sub(r"^(?:\d+[\).:-]|q\d+\s*[:.)-]|question\s*\d+\s*[:.)-])\s*", "", question, flags=re.I)
    if not question:
        return ""
    if question[-1] not in ".?!":
        question += "?"
    return question


def parse_generated_skill_questions(raw: str, skill_names: Sequence[str], count: int = 3) -> Dict[str, List[str]]:
    """Parse Qwen's upload-time JSON into {skill: [q1, q2, q3]}."""
    blob = (raw or "").strip()
    blob = re.sub(r"^```(?:json)?\s*", "", blob, flags=re.I)
    blob = re.sub(r"\s*```$", "", blob).strip()
    if not blob:
        return {}
    try:
        parsed = json.loads(blob)
    except Exception:
        match = re.search(r"\{[\s\S]+\}", blob)
        if not match:
            return {}
        try:
            parsed = json.loads(match.group(0))
        except Exception:
            return {}

    rows = parsed.get("slots") if isinstance(parsed, dict) else parsed
    by_name: dict[str, list[str]] = {}
    if isinstance(parsed, dict) and not isinstance(rows, list):
        for key, value in parsed.items():
            if str(key).lower() in {"slots", "skills"}:
                continue
            if isinstance(value, list):
                by_name[str(key).strip().lower()] = value
    if isinstance(rows, list):
        for row in rows:
            if not isinstance(row, dict):
                continue
            name = str(row.get("skill") or row.get("name") or "").strip()
            qs = row.get("questions") or row.get("qs") or []
            if name and isinstance(qs, list):
                by_name[name.lower()] = qs

    out: dict[str, list[str]] = {}
    for skill in skill_names:
        raw_qs = by_name.get(str(skill).strip().lower()) or []
        cleaned: list[str] = []
        seen: set[str] = set()
        for item in raw_qs:
            question = _clean_generated_question(item)
            key = _norm_question(question)
            if not question or len(question.split()) < 6 or key in seen:
                continue
            seen.add(key)
            cleaned.append(question)
            if len(cleaned) >= count:
                break
        if len(cleaned) >= count:
            out[str(skill)] = cleaned[:count]
    return out


async def generate_skill_questions_with_qwen(
    plan: Dict[str, Any],
    candidate_dict: Dict[str, Any] | None = None,
) -> Dict[str, Any]:
    """
    Replace fallback skill questions with Qwen-written ones.

    Runs at resume upload / agenda preview so the live interview only phrases
    them. Project follow-ups stay live GENERATE.
    """
    plan = dict(plan or {})
    slots = list(plan.get("skill_slots") or [])
    if not slots or str(plan.get("skill_questions_source") or "") == "qwen":
        return plan

    candidate_dict = candidate_dict or {}
    name = candidate_dict.get("name") or "the candidate"
    role = candidate_dict.get("target_role") or candidate_dict.get("role") or "the role"
    count = max(3, int(plan.get("questions_per_skill") or 3))
    skill_names = [slot.get("skill") for slot in slots if slot.get("skill")]

    payload = {
        "candidate": name,
        "role": role,
        "skills_in_order": [
            {"skill": slot.get("skill"), "kind": slot.get("kind") or "cv"}
            for slot in slots if slot.get("skill")
        ],
        "questions_per_skill": count,
        "per_skill_cv_terms": {slot.get("skill"): slot.get("cv_terms") or [] for slot in slots},
    }
    system = (
        "You write skill-phase questions for a live technical interview.\n"
        "Python already chose the skill list and order. You write the questions now, "
        "before the call, so the live turn is fast.\n"
        "Rules:\n"
        "1. For EVERY skill in skills_in_order write exactly "
        f"{count} distinct technical questions.\n"
        "2. Skills and projects are SEPARATE. Never mention a project name. "
        "Never ask them to walk through a CV project or how they used a skill inside one.\n"
        "3. kind=foundation (Object-Oriented Programming, Data Structures and Algorithms): "
        "ask classic CS only — classes, objects, inheritance, polymorphism, encapsulation, "
        "arrays, hash maps, stacks, queues, linked lists, sorting, time complexity. "
        "Do not mention models, datasets, or projects.\n"
        "4. kind=cv: ask what that language or library is and how it works in simple terms. "
        "You may name libraries that belong to that skill. Do not name projects.\n"
        "5. Q1 is foundational. Q2 is how it works. Q3 is a simple trade-off or limitation.\n"
        "6. Each question is one spoken sentence ending with ?\n"
        "7. Return ONLY JSON: "
        '{"slots":[{"skill":"...","questions":["...","...","..."]}]}'
    )
    try:
        from interviewer.adapters.registry import get_llm
        from interviewer.ports.llm import LLMRequest, LLMTask, Message

        result = await get_llm().complete(
            LLMRequest(
                task=LLMTask.EXTRACT,
                messages=[
                    Message(role="system", content=system),
                    Message(role="user", content=json.dumps(payload, ensure_ascii=False)),
                ],
                temperature=0.4,
                max_tokens=900,
            )
        )
        generated = parse_generated_skill_questions(result.text if result.ok else "", skill_names, count)
    except Exception:
        generated = {}

    if not generated:
        return plan

    filled = 0
    for slot in slots:
        skill = slot.get("skill")
        questions = generated.get(skill)
        if not questions:
            continue
        slot["questions"] = questions
        slot["base_question"] = questions[0]
        slot["question_ids"] = []
        slot["source"] = "qwen"
        filled += 1
    plan["skill_slots"] = slots
    if filled:
        plan["skill_questions_source"] = "qwen"
    return plan
